[package]
name = "anc-assembly"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anc-isa = { path = "../../../xiaoxuan-core-isa" }

[dev-dependencies]
pretty_assertions = "1.4.1"
